### ISSUE TITLE
Compiling Errors - javaoboject error

### ISSUE THREAD

**Issue by OJ3D** [zeh/unity-tidbits#1]
Zeh - thanks for the share. I got the following build errors below:

The type arguments for method `UnityEngine.AndroidJavaObject.GetStatic<FieldType>(string)' cannot be inferred from the usage. Try specifying the type arguments explicitly

I'm using Unity 5.2.3

**Comment by zeh** [comment]
Hey man, thanks for the issue entry and the PR. I'll be reviewing the PR now and providing some feedback, but in the meantime - what is the Android version you're using for testing? I have a game currently in development using this class (using on Unity 5.3, and lately testing on Android 6) and it's working as expected. I'm sure the error exists, but I want to be able to reproduce it - I think it's probably related to a specific Android version that I might not have tested against.

**Comment by IanPozz** [comment]
Hi, I'm having the same problem as @OJ3D.  I'm using Unity 5.3.5 and Mono 5.9.6.  When I try to compile the class I get errors as the calls to unityPlayer.GetStatic use generics and expect a class to be passed.  The documentation shows what's required:

https://docs.unity3d.com/ScriptReference/AndroidJavaObject.GetStatic.html

Can you advise why we're seeing this problem?

Thanks.

**Comment by zeh** [comment]
Hey @IanPozz,

Sorry for the delay in responding, was away.

The [current version of `ApplicationChrome.cs`](https://github.com/zeh/unity-tidbits/blob/master/application/ApplicationChrome.cs) does pass the class to the generic method.

Here's an idea: you might have copied the code from [my blog post](http://zehfernando.com/2015/unity-tidbits-changing-the-visibility-of-androids-navigation-and-status-bars-and-implementing-immersive-mode/) on the subject. I just realized that when I last updated the code to match the repository version, I forgot to replace `<` and `>` with `&lt;` and `&gt;`, so all the generic castings disappeared as they were interpreted as HTML tags. That is fixed now.

So do you mind updating your code, either with [the repo version of  `ApplicationChrome.cs`](https://github.com/zeh/unity-tidbits/blob/master/application/ApplicationChrome.cs) or the blog post example, and trying again? It should probably fix the problem.

And sorry about that.

**Comment by zeh** [comment]
I've tested the current version on latest Unity (2019.3) and it seems to work well without syntax problems (apart from the bug in #4), so I'm closing this.

Let me know if any problems still persist and I'll revisit it.
