### ISSUE TITLE
Navigation bar color does not work

### ISSUE THREAD

**Issue by doggan** [zeh/unity-tidbits#3]
I'm using your ApplicationChrome (https://github.com/zeh/unity-tidbits/blob/master/application/ApplicationChrome.cs) script.

I've set both status bar and navigation bar to visible, and I set the colors for both. The status bar color works, but the navigation bar color does not change from its default grey color.

I've also tried running your demo APK (http://zehfernando.com/d/2015/UnityAndroidChrome.apk), and it has the same issue.

For reference, I'm running it on an LG G6 running Android 7.0.

p.s. This script has been very useful. Thanks for releasing it 🎉

**Comment by AVAVT** [comment]
Just in case someone will come here in the future, this is how I managed to set custom color for navigation bar:
```
ApplicationChrome.statusBarState = ApplicationChrome.States.TranslucentOverContent;
ApplicationChrome.statusBarColor = ApplicationChrome.navigationBarColor = 0xff222222;
```

The caveat is that you must have statusBar at Translucent.

**Comment by zeh** [comment]
Thanks for the answer @AVAVT.

Agreed that the API is somewhat confusing - it does have to be translucent. Android's UI flags are weird...

I'm working on a revision of the library and will hopefully have a more clear API.

For now, I'll close this as I think there's no additional changes needed.
